In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
texts = ['자연어 처리 알고리즘', '자연어 처리 방법',
         '자연어 NLP 알고리즘 알고리즘',
         '자연어 처리 전문가']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tok = Tokenizer()

In [ ]:
tok.fit_on_texts(texts)

In [ ]:
tok.index_word

{1: '자연어', 2: '처리', 3: '알고리즘', 4: '방법', 5: 'nlp', 6: '전문가'}

In [ ]:
# 말 그대로, 텍스트를 매트릭스로 바꿔준다. (원핫인코딩)
tok.texts_to_matrix(texts, mode='binary') # default mode = 'binary

array([[0., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 1.]])

In [ ]:
tok.texts_to_matrix(texts, mode='count') # 몇 번 등장했느냐에 따라 수치를 바꿔줌.

array([[0., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 1., 0., 0.],
       [0., 1., 0., 2., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 1.]])

In [ ]:
tok.texts_to_matrix(texts, mode='tfidf') # tfidf matrix를 생성

array([[0.        , 0.58778666, 0.69314718, 0.84729786, 0.        ,
        0.        , 0.        ],
       [0.        , 0.58778666, 0.69314718, 0.        , 1.09861229,
        0.        , 0.        ],
       [0.        , 0.58778666, 0.        , 1.43459998, 0.        ,
        1.09861229, 0.        ],
       [0.        , 0.58778666, 0.69314718, 0.        , 0.        ,
        0.        , 1.09861229]])

In [ ]:
tok.texts_to_matrix(texts, mode='freq') # frequency ratio (빈도 비율 - 잘 안씀)

array([[0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ,
        0.        , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.        , 0.33333333,
        0.        , 0.        ],
       [0.        , 0.25      , 0.        , 0.5       , 0.        ,
        0.25      , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.        , 0.        ,
        0.        , 0.33333333]])

In [ ]:
from google.colab import drive
drive.mount('/content/myDrive')

Mounted at /content/myDrive


In [ ]:
import pandas as pd
import numpy as np
from string import punctuation

In [ ]:
df = pd.read_csv('/content/myDrive/MyDrive/data/datasets/NYT_2018.csv')

In [ ]:
df.columns

Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')

In [ ]:
df.head()

articleID  articleWordCount  \
0  5adf6684068401528a2aa69b               781   
1  5adf653f068401528a2aa697               656   
2  5adf4626068401528a2aa628              2427   
3  5adf40d2068401528a2aa619               626   
4  5adf3d64068401528a2aa60f               815   

                                      byline documentType  \
0                             By JOHN BRANCH      article   
1                           By LISA FRIEDMAN      article   
2                              By PETE WELLS      article   
3  By JULIE HIRSCHFELD DAVIS and PETER BAKER      article   
4             By IAN AUSTEN and DAN BILEFSKY      article   

                                            headline  \
0  Former N.F.L. Cheerleaders’ Settlement Offer: ...   
1  E.P.A. to Unveil a New Rule. Its Effect: Less ...   
2                            The New Noma, Explained   
3                                            Unknown   
4                                            Unknown   

                                            keywords  multimedia     newDesk  \
0  ['Workplace Hazards and Violations', 'Football...          68      Sports   
1  ['Environmental Protection Agency', 'Pruitt, S...          68     Climate   
2  ['Restaurants', 'Noma (Copenhagen, Restaurant)...          66      Dining   
3  ['Macron, Emmanuel (1977- )', 'Trump, Donald J...          68  Washington   
4  ['Toronto, Ontario, Attack (April, 2018)', 'Mu...          68     Foreign   

   printPage              pubDate   sectionName  \
0          0  2018-04-24 17:16:49  Pro Football   
1          0  2018-04-24 17:11:21       Unknown   
2          0  2018-04-24 14:58:44       Unknown   
3          0  2018-04-24 14:35:57        Europe   
4          0  2018-04-24 14:21:21        Canada   

                                             snippet              source  \
0  “I understand that they could meet with us, pa...  The New York Times   
1  The agency plans to publish a new regulation T...  The New York Times   
2  What’s it like to eat at the second incarnatio...  The New York Times   
3  President Trump welcomed President Emmanuel Ma...  The New York Times   
4  Alek Minassian, 25, a resident of Toronto’s Ri...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2018/04/24/sports/foot...  
1           News  https://www.nytimes.com/2018/04/24/climate/epa...  
2           News  https://www.nytimes.com/2018/04/24/dining/noma...  
3           News  https://www.nytimes.com/2018/04/24/world/europ...  
4           News  https://www.nytimes.com/2018/04/24/world/canad...

In [ ]:
headline = df.headline

In [ ]:
len(headline)

1324

In [ ]:
headline.head()

0    Former N.F.L. Cheerleaders’ Settlement Offer: ...
1    E.P.A. to Unveil a New Rule. Its Effect: Less ...
2                              The New Noma, Explained
3                                              Unknown
4                                              Unknown
Name: headline, dtype: object

In [ ]:
len(headline[headline=='Unknown'])

110

In [ ]:
df.headline=='Unkknown'

0       False
1       False
2       False
3       False
4       False
        ...  
1319    False
1320    False
1321    False
1322    False
1323    False
Name: headline, Length: 1324, dtype: bool

In [ ]:
headline = df.headline[headline!='Unknown'] # unknown 제거

In [ ]:
len([w for w in headline if w =='Unknown'])  #=='Unknown

0

Series를 List로 바꿔서 count하는 게 제일빠르다. (의외)

In [ ]:
%%timeit

sum(df.headline == 'Unknown')

705 µs ± 338 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%%timeit

len([w for w in headline if w=='Unknown'])

177 µs ± 55.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%%timeit

head_list = list(headline)
head_list.count('Unknown')

170 µs ± 53.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# headline에 저장된 뉴스 기사 제목으로 다음 단어를 생성하는 LSTM
'''
기반 모델 설계
<동작 예시>

입력 : I, 생성하고자 하는 단어의 갯수
출력 : I was ... 완성
'''

In [ ]:
head_list[0]

'Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell'

In [ ]:
def pre_func(title):
  # 소문자 변환
  # res = title.lower()
  global punctuation
  # 문자열 하나하나를 w로 받아서 lower를 해주는 코드
  # w가 punctuation에 속하지 않으면(특수문자면) 넣어줘라. (== str.isalpha() 라는 좋은 함수가 있음)
  res = ''.join([w.lower() for w in title if w not in punctuation])
  return res

In [ ]:
# 전처리
# [x.lower() for x in headline]
pre_headline = [pre_func(x) for x in headline]
pre_headline[:5]

['former nfl cheerleaders’ settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [ ]:
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
tok = Tokenizer()
tok.fit_on_texts(pre_headline)

In [ ]:
type(tok.index_word)

dict

In [ ]:
len(tok.index_word)

3619

In [ ]:
vocab_size = len(tok.index_word) +1

In [ ]:
sequences = []
for s in pre_headline:
  enc = tok.texts_to_sequences([s])[0]
  for i in range(1, len(enc)):

    seq = enc[: i+1]
    sequences.append(seq)

sequences[:15]

[[95, 263],
 [95, 263, 1100],
 [95, 263, 1100, 1101],
 [95, 263, 1100, 1101, 572],
 [95, 263, 1100, 1101, 572, 50],
 [95, 263, 1100, 1101, 572, 50, 7],
 [95, 263, 1100, 1101, 572, 50, 7, 2],
 [95, 263, 1100, 1101, 572, 50, 7, 2, 365],
 [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10],
 [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10, 1102],
 [96, 3],
 [96, 3, 1103],
 [96, 3, 1103, 2],
 [96, 3, 1103, 2, 14],
 [96, 3, 1103, 2, 14, 573]]

In [ ]:
sents = [
    ['programmer', 'person'],
    ['programmer', 'word', 'secret']]

In [ ]:
mytok = Tokenizer()
mytok.fit_on_texts(sents)
mytok.word_index

{'programmer': 1, 'person': 2, 'word': 3, 'secret': 4}

In [ ]:
# 문자 그대로 텍스트를 시퀀스형 자료로 바꿔줌.
mytok.texts_to_sequences(sents)

[[1, 2], [1, 3, 4]]

In [ ]:
# list로 감싸주지 않으면
alpha_tok = Tokenizer()
alpha_tok.fit_on_texts('asbs dfadf fasdf dfsdf aqw er')

In [ ]:
alpha_tok.word_index

{'f': 1, 'd': 2, 'a': 3, 's': 4, 'b': 5, 'q': 6, 'w': 7, 'e': 8, 'r': 9}

In [ ]:
text_tok = Tokenizer()
text_tok.fit_on_texts(['asdf asdf  bwrq sdf ax d f s fasd ddd'])

In [ ]:
text_tok.word_index

{'asdf': 1,
 'bwrq': 2,
 'sdf': 3,
 'ax': 4,
 'd': 5,
 'f': 6,
 's': 7,
 'fasd': 8,
 'ddd': 9}

In [ ]:
mytok.word_index

{'programmer': 1, 'person': 2, 'word': 3, 'secret': 4}

In [ ]:
sequences[:15]

[[95, 263],
 [95, 263, 1100],
 [95, 263, 1100, 1101],
 [95, 263, 1100, 1101, 572],
 [95, 263, 1100, 1101, 572, 50],
 [95, 263, 1100, 1101, 572, 50, 7],
 [95, 263, 1100, 1101, 572, 50, 7, 2],
 [95, 263, 1100, 1101, 572, 50, 7, 2, 365],
 [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10],
 [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10, 1102],
 [96, 3],
 [96, 3, 1103],
 [96, 3, 1103, 2],
 [96, 3, 1103, 2, 14],
 [96, 3, 1103, 2, 14, 573]]

In [ ]:
'''
ex) lstm 모델로 단어를 예측하도록 설계합니다.
입력                -                   출력
---------------------------------------------
lstm                                  모델로
lstm 모델로                           단어를
...
lstm 모델로 단어를 예측하도록       설계합니다.
-----------------------------------------------

입력값 x1 -> x2  출력으로 학습
입력값 x1, x2 => x3  출력으로 학습
...
입력값 x1, x2, ..., x(n-1)  =>  x(n) 학습

<입력>
# ~ 만약 kstm이란 게 들어오면 어떻게 될까??
## - 파이썬의 if조건문과 다르게, lstm과 유사한 단어로 판단하고, 예측이 가능하다.

토큰이 n개면 n-1개의 학습결과가 나오게 된다.

<출력>
그럼 출력층의 shape은 어떻게 될까?
>> 모든 단어들이 y값에서 나올 수 있기 때문에
>> 단어사전의 크기(모든 단어의 수)만큼 출력층의 크기를 갖는다. (y1 = 모델로, y2= 단어를, ..., yn = 설계합니다.)
'''


'\nex) lstm 모델로 단어를 예측하도록 설계합니다.\n입력                -                   출력\n---------------------------------------------\nlstm                                  모델로\nlstm 모델로                           단어를\n...\nlstm 모델로 단어를 예측하도록       설계합니다.\n-----------------------------------------------\n\n입력값 x1 -> x2  출력으로 학습\n입력값 x1, x2 => x3  출력으로 학습\n...\n입력값 x1, x2, ..., x(n-1)  =>  x(n) 학습\n\n<입력>\n# ~ 만약 kstm이란 게 들어오면 어떻게 될까??\n## - 파이썬의 if조건문과 다르게, lstm과 유사한 단어로 판단하고, 예측이 가능하다.\n\n토큰이 n개면 n-1개의 학습결과가 나오게 된다.\n\n<출력>\n그럼 출력층의 shape은 어떻게 될까?\n>> 모든 단어들이 y값에서 나올 수 있기 때문에\n>> 단어사전의 크기(모든 단어의 수)만큼 출력층의 크기를 갖는다. (y1 = 모델로, y2= 단어를, ..., yn = 설계합니다.)\n'

```python
tf.keras.layers.LSTM(
    units,
    activation="tanh",
    recurrent_activation="sigmoid",
    use_bias=True,
    kernel_initializer="glorot_uniform",
    recurrent_initializer="orthogonal",
    bias_initializer="zeros",
    unit_forget_bias=True,
    kernel_regularizer=None,
    recurrent_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    recurrent_constraint=None,
    bias_constraint=None,
    dropout=0.0,
    recurrent_dropout=0.0,
    return_sequences=False,
    return_state=False,
    go_backwards=False,
    stateful=False,
    time_major=False,
    unroll=False,
    **kwargs
)
```

**return_sequences = False,**  
모든 시퀀스를 출력값을 줄 건지에 대한 여부  
LSTM같은 경우, 다대일 계층.  
즉, 입력값이 n-1개, 출력값이 1개로 이루어져있는데  
return_sequences=True를 주게 되면 이 구조가 망가진다.

In [ ]:
len(tok.word_index)

3619

In [ ]:
type(tok.word_index)

dict

In [ ]:
idx2word= {}

# 가장 빈도수가 높은 게 가장 위에 위치하게 된다.
# key, value 쌍을 바꾸는 딕셔너리 생성
for k, v in tok.word_index.items():
  idx2word[v] = k

idx2word

In [ ]:
sequences

In [ ]:
maxlen = print(max(len(i) for i in sequences))

24


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
# 원핫인코딩 비슷한 느낌인데 0 1 대신 단어사전의 인덱스로 들어감.
padded_sequences = pad_sequences(sequences, maxlen=maxlen, padding='pre')
padded_sequences.shape

(7809, 24)

In [ ]:
padded_sequences[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  95, 263], dtype=int32)

In [ ]:
x_data = np.array([sequence[:-1] for sequence in padded_sequences])
y_data = np.array([sequence[-1] for sequence in padded_sequences])

In [ ]:
# 다른 표현방법.
array_sequences = np.array(padded_sequences)
x_data = array_sequences[:,:-1] # 전체에 대해서, 처음부터 -1번째 인덱스까지만 (슬라이싱)
y_data = array_sequences[:,-1] # 전체에 대해서, -1번째 인덱스만 (인덱싱)

In [ ]:
x_data.shape

(7809, 23)

In [ ]:
y_data.shape

(7809,)

In [ ]:
print(x_data[0], y_data[0])

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 95] 263


In [ ]:
# y값에 대해 출력값을 categorical value 값으로 변환하기 위함
# y값 출력층 shape 1 -> 3620
from tensorflow.keras.utils import to_categorical

In [ ]:
y_cat = to_categorical(y_data, vocab_size)

In [ ]:
y_cat.shape

(7809, 3620)

In [ ]:
from tensorflow.keras.layers import Dense, Embedding
from tensorflow.keras.models import Sequential

In [ ]:
vocab_size

3620

In [ ]:
# 모델 오브젝트 생성
model = Sequential()

# 모델 층 쌓기
from tensorflow.keras.layers import LSTM # layer로 사용할 LSTM

# EmbeddingVector 생성, 3620차원을 10차원으로 변경
model.add(Embedding(vocab_size, 10)) # input 3620 -> maxlen(24) ->  hidden 10
model.add(LSTM(128)) # hidden 10 -> hidden 128 (특성의 갯수 정도로 의미하면 됨. 몇 가지의 특성으로 나타낼 것인가)
model.add(Dense(vocab_size, activation='softmax')) # hidden 128 -> output 3620(단어예측) w/ softmax

In [ ]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, None, 10)          36200     
                                                                 
 lstm_4 (LSTM)               (None, 128)               71168     
                                                                 
 dense_4 (Dense)             (None, 3620)              466980    
                                                                 
Total params: 574,348
Trainable params: 574,348
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# embedding의 구조가 신경망의 구조와 굉장히 유사하다.
# loss = 노드값 하나하나에 대한 error를 의미한다.
# cost = cost function : (loss들의 합 / 노드의 갯수) 를 사용한 비용함수, MSE 많이씀

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
x_data.shape

(7809, 23)

In [ ]:
y_cat.shape

(7809, 3620)

In [ ]:
model.fit(x_data, y_cat, epochs=200, )

In [ ]:
# 다음에 올 단어 예측
def gen_sent(model, token, c_word, n):
  pred_sent = ""

  for _ in range(10):
    # 구현
    enc = tok.texts_to_sequences([c_word])[0]
    enc = pad_sequences([enc], maxlen=24, padding='pre')

    # 예측
    pred = model.predict(enc)
    # print(pred)

    # argmax _ 예측값이 최대가 되는 arguments(단어) 찾기
    res = np.argmax(pred)

    # word : index 순서로 저장되어있는 딕셔너리.
    for word, idx in tok.word_index.items():
      if res == idx:
        break

    c_word = c_word + ' ' + word # The => The New
    print("예측 단어: ", word)
    pred_sent = c_word

  return pred_sent

# 입력 ( 모델, 토크나이저, 단어, 예측 할 단어의 수 n)


In [ ]:
gen_sent(model, tok, 'The', 10)

1/1 [==============================] - 0s 76ms/step
예측 단어:  new
1/1 [==============================] - 0s 71ms/step
예측 단어:  shingles
1/1 [==============================] - 0s 107ms/step
예측 단어:  vaccine
1/1 [==============================] - 0s 87ms/step
예측 단어:  reasons
1/1 [==============================] - 0s 38ms/step
예측 단어:  to
1/1 [==============================] - 0s 44ms/step
예측 단어:  get
1/1 [==============================] - 0s 54ms/step
예측 단어:  it
1/1 [==============================] - 0s 48ms/step
예측 단어:  the
1/1 [==============================] - 0s 52ms/step
예측 단어:  white
1/1 [==============================] - 0s 103ms/step
예측 단어:  white


'The new shingles vaccine reasons to get it the white white'

In [ ]:
# GPU 가속기 사용하기 w/ Cuda
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at :{}'.format(device_name))

Found GPU at :/device:GPU:0


In [ ]:
# 모델 층 쌓기
from tensorflow.keras.layers import LSTM # layer로 사용할 LSTM
from tensorflow.keras.layers import Dense, Embedding # FCL, Embedding Vector
from tensorflow.keras.models import Sequential

with tf.device('/device:GPU:0'):
  # 모델 오브젝트 생성
  model = Sequential()

  # EmbeddingVector 생성, 3620차원을 10차원으로 변경
  model.add(Embedding(vocab_size, 10)) # input 3620 -> maxlen(24) ->  hidden 10
  model.add(LSTM(128, return_sequences=True)) # hidden 10 -> hidden 128 (특성의 갯수 정도로 의미하면 됨. 몇 가지의 특성으로 나타낼 것인가)
  model.add(LSTM(256, return_sequences=True))
  model.add(LSTM(128, return_sequences=True))
  model.add(LSTM(64))
  model.add(Dense(vocab_size, activation='softmax')) # hidden 128 -> output 3620(단어예측) w/ softmax
  # embedding의 구조가 신경망의 구조와 굉장히 유사하다.

  # loss = 노드값 하나하나에 대한 error를 의미한다.
  # cost = cost function : (loss들의 합 / 노드의 갯수) 를 사용한 비용함수, MSE 많이씀
  model.compile(loss='categorical_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])

  # 학습
  model.fit(x_data, y_cat, epochs=200, verbose=2)

Epoch 1/200
245/245 - 20s - loss: 7.7087 - accuracy: 0.0255 - 20s/epoch - 82ms/step
Epoch 2/200
245/245 - 3s - loss: 7.2232 - accuracy: 0.0306 - 3s/epoch - 13ms/step
Epoch 3/200
245/245 - 3s - loss: 7.1645 - accuracy: 0.0303 - 3s/epoch - 12ms/step
Epoch 4/200
245/245 - 4s - loss: 7.1419 - accuracy: 0.0301 - 4s/epoch - 15ms/step
Epoch 5/200
245/245 - 3s - loss: 7.1323 - accuracy: 0.0307 - 3s/epoch - 12ms/step
Epoch 6/200
245/245 - 3s - loss: 7.1262 - accuracy: 0.0305 - 3s/epoch - 12ms/step
Epoch 7/200
245/245 - 3s - loss: 7.1228 - accuracy: 0.0291 - 3s/epoch - 12ms/step
Epoch 8/200
245/245 - 3s - loss: 7.1215 - accuracy: 0.0314 - 3s/epoch - 11ms/step
Epoch 9/200
245/245 - 4s - loss: 7.1195 - accuracy: 0.0314 - 4s/epoch - 17ms/step
Epoch 10/200
245/245 - 3s - loss: 7.1176 - accuracy: 0.0314 - 3s/epoch - 12ms/step
Epoch 11/200
245/245 - 3s - loss: 7.1166 - accuracy: 0.0311 - 3s/epoch - 11ms/step
Epoch 12/200
245/245 - 3s - loss: 7.1147 - accuracy: 0.0307 - 3s/epoch - 11ms/step
Epoch 13/20

In [ ]:
# 우리나라 소설 책(토지) 중 일부를 발췌하여 모델링 연습 (선택사항)
# 한자 제거하고 띄어쓰기 기준으로 토큰화
# 불용어 제거하고...동의어처리 해야되나?
# okt 이용해서 명사(nouns)만 뽑기. # 형태소분석기 써도됨