In [ ]:
import re

In [ ]:
# re.함수명(패턴, 문자열)
re.search('^Hello', 'Hello, world!') # Hello 로 시작하는 단어를 찾아줌.

<re.Match object; span=(0, 5), match='Hello'>

In [ ]:
re.search('^Hello', 'Hi Hello, world!') # Hi 로 시작했기 때문에 return 값이 없음.

In [ ]:
re.search('world!$', 'Hello, world') # world로 끝나는지를 판단

In [ ]:
re.match('hello|world', 'hello') # hello 또는 world가 있으면 return

<re.Match object; span=(0, 5), match='hello'>

In [ ]:
re.findall('[0-9]*', '1234') # 1234라는 문자열 속에 패턴이 있습니까?

['1234', '']

In [ ]:
re.findall('[0-9]+', '1234')

['1234']

In [ ]:
'''
안녕하세요 오늘부터 함께 알고리즘 진행할 스터디방입니다.
오늘부터 부담되지 않는 선에서 함께 스터디를 진행해보려고 합니다.

'''

# [] 한 문자
# ex) [a] : a문자 의미, [ab] : a또는 b문자 의미
# ex) [a-c] : a부터 c까지의 문자를 의미

'\n안녕하세요 오늘부터 함께 알고리즘 진행할 스터디방입니다.\n오늘부터 부담되지 않는 선에서 함께 스터디를 진행해보려고 합니다.\n\n'

In [ ]:
re.match('[0-9]*', '1234') # 숫자가 0개 이상 존재하면 매치

<re.Match object; span=(0, 4), match='1234'>

In [ ]:
re.match('[0-5]*', '1234' )

<re.Match object; span=(0, 4), match='1234'>

In [ ]:
re.match('[5-9]*', '1234')

<re.Match object; span=(0, 0), match=''>

In [ ]:
re.match('[0-9a-zA-Zㄱ-ㅎ가-힣]*', 'ㅋㅋㅋ홍길동XYabc1234')

<re.Match object; span=(0, 15), match='ㅋㅋㅋ홍길동XYabc1234'>

In [ ]:
re.match('[0-9]+', 'rk1234') # 맨 앞에서 일치하는게 아니면 return하지 않음. (그래서 잘 안씀)

In [ ]:
re.match('[0-9]+[가-힣]+[0-9]', '12가34')

<re.Match object; span=(0, 4), match='12가3'>

In [ ]:
re.match('[0-9]+[가-힣]+[0-9]+', '12가34')

<re.Match object; span=(0, 5), match='12가34'>

In [ ]:
re.match('[0-9]+[가-힣]+[0-9]+aa', '12가34abc') # 아무것도 나오지 않는다. (aa를 일치시켜야 하기 때문에)

In [ ]:
re.match('h{3}', 'hhhelllo')  # {반복횟수}

<re.Match object; span=(0, 3), match='hhh'>

In [ ]:
m = re.match('(?P<func>[a-zA-Z_][a-zA-Z0-9_]+)\((?P<arg>\w+)\)', 'print1234')
# ?P<func> 함수를 만든다.
# _ 한글자 이상

re.search('[0-9]+', 'Fizz 1 2 4 Buzz Fizz 7 8')

<re.Match object; span=(5, 6), match='1'>

In [ ]:
# 연습문제 : 뉴스기사에서 특정 문자들만 추출 (findall 사용하기)

In [ ]:
re.findall('[0-9]+', 'Fizz 1 2 4 Buzz Fizz 7 8') # 모든 숫자를 다 찾아버림

['1', '2', '4', '7', '8']

In [ ]:
'''
언어모델 : 통계적 모델, 신경망 모델
통계적(ML) 기반 모델 : 초창기 모델로, 지금은 잘 쓰이지 않음.
신경망(NN) 기반 모델 : LSTM, RNN 등

언어모델은 언어에 대한 순서에 확률을 부여하여 문장 또는 단어를 추출하거나 예측하는 모델


---------------------------------------------------------------------
-- Statistic Language Model (SLM)
통계적 기반 모델 : 단어의 순서에 대해 확률을 부여
ex) P(나는 자연어 처리를 공부한다.) > P(나는 자연어 처리를 먹는다.)
전자에 대한 확률이 더 높다.==> 추천
P(공부한다 | 나는 , 자연어, 처리)


n-gram : 문장간의 유사도를 비교할 때 쓰이는 방법.
    ex) 오늘 점심 추천 메뉴:소고기볶음밥, 햄볶음밥

# 보통 바이그램까지 많이쓰인다.
유니그램:(n=1) : 오늘, 점심, 추천, 메뉴...
바이그램 (n=2) : 오늘 점심, 점심 추천, 추천 메뉴 ...
트라이그램(n=3) : 오늘 점심 추천, 점심 추천 메뉴, 추천 메뉴 소고기볶음밥...

P(소고기볶음밥 | 점심 추천 메뉴)
  = count(소고기 볶음밥 with 점심 추천 메뉴) / count(점심 추천 메뉴)
...
2000-2010 초반의 전통적 통계 기반 언어모델 ~ 굉장히 한계가 많음.
(조금만 수정되어도 적용이 안됨.)
ex) 점심 추천 메뉴 -> 저녁 추천 메뉴
ex) 점심 -> 런치  // 메뉴 -> 메뉴판

또한 n을 얼마나 할 것인가 등에 대해 정하기가 쉽지 않음.
(대부분 unigram이 좋은 성능을 낸다고 나오긴 하지만...)

* 시간이 되면 나중에 LCS(Longest Common Seubsequence) 알고리즘 공부하기.
>>> 코테 단골문제.


1. 한국어는 단어의 순서가 큰 의미 없음
-> 신경망(RNN, LSTM) 기반 생성시 어려움


<얕은 신경망>
Linear Regression(예측, 회귀) -> Logistic Regression(Sigmoid 이진분류)
  -> SOFTMAX(다중분류) -> (얕은 신경망) : NN - Nueral Neetwork

h(x) = wx + b # linear regression // ~inf ~ + inf
sigmoid(h(x)) = 1 / 1 + e^-(h(x)) // 0 ~ 1
SOFTMAX --> 각 선택지별로 sigmoid를 적용, 가장 높은 확률의 class선택
위의 소프트맥스를 사용한 Neural Network가 얕은 신경망

<깊은 신경망>
(신경망 종류 - DNN, CNN, RNN 등)
입력 / 히든 / 출력 레이어(층)으로 구분되어 구분함.
-----------------------------------------------------------------------

나는 지금 자연어를 공부해요
자연어를 공부해요 나는 지금
> 둘 다 해석이 가능함.
'''

In [ ]:
'''
## TF-IDF (Term Frequency - Inverse Document Frequency)

one-hot, DTM(Document Term Matrix - TF), TDM, TF-IDF

DTM ----------------------------------
         단어 1    단어 2 ...   단어N  |
문서1 |     5        0     ...     0   |  M차원 벡터 공간(5, 0, 1)
문서2 |     3        2     ...     1   |
...   |                                |
문서N |     1        4     ...     3   |
--------------------------------------

Q) 어떻게 추천할 수 있을까?
1) 문서 1과 다른 문서 사이의 유클리디안 거리를 비교하여 추천
>>> KNN - 최인접 이웃들을 유클리디안 거리로 추천해줌
'''

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
# CountVectorizer : 단어의 빈도수를 기반으로 벡터를 생성하는 함수.


In [ ]:
corpus = ['나는 지금 자연어 처리를 공부해요. 나는 자연어 좋아요']

In [ ]:
vector = CountVectorizer() # object 생성

In [ ]:
'''
fit 결과
>>> [2 1 2 1 1 1 ]
sparse matrix(희소행렬: 행렬 요소값이 대부분이 0인 행렬) -- 공간 낭비, 연산량 폭발적
'''

vector.fit_transform(corpus) # unique한 단어들만 뽑아서 사전에 넣어줌
# fit: 각각의 단어별로 인덱스 부여
# transform: corpus에 저장된 문장을 fit 결과에 맞춰 (빈도수 기반)변환해라.

<1x6 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
vector.fit_transform(corpus).toarray()

array([[1, 2, 2, 1, 1, 1]])

In [ ]:
# Bag of Words (BOW)
vector.vocabulary_

{'나는': 1, '지금': 4, '자연어': 2, '처리를': 5, '공부해요': 0, '좋아요': 3}

In [ ]:
'''
cosine similarity (코사인 유사도)
- A벡터와 B벡터간의 내적을 통해 이루는 각을 비교할 수 있음.
- 코사인90도까지만 비교하면 됨
  - why?) 빈도수는 음수값이 나올 수 없기 때문에 90도를 넘을 수 없음.

K-MEANS
- 선형 기반 클러스터링
- 거리 기반 (K값의 랜덤한 센트로이드 기준으로 유클리디안 거리를 측정 후 가까운 것부터 클러스터화)


DBSCAN
- 거리 기반 클러스터링 (특정 관측값 y로부터 반경 r 안에 들어가는 점들의 모임)

H_Clustering
- 계층형 클러슽터링 모델

> seaborn.pairplot 써봅시다 (코사인 유사도와 밀접한가?)
----------------------------------------------------------------

## tf-idf
==> TDM을 tf * idf 값의 매트릭스로 변경

<tf-idf 개념>
한 문서에서 더 자주 보일수록(specific할수록) 가중치를 높게주고. -- term frequency
여러 문서에서 쉽게 보일수록(general할수록) 가중치를 낮게준다. -- inverse document frequenccy

tf(d, t) : 특정 문서 d에서 찾는 단어 t가 나오는 빈도수 (term | docu_n)
idf(d, t) : 't가 등장하는 모든 문서 documents의 개수' 의 역수(inverse)

ex) 내가 찾고싶은건 '흑맥주', 검색어의 범용성 --> '맥주' 가 더 많이 나온다 ==> df 상승
     --> 특정 문서에서 '흑맥주'가 '맥주'보다 tf가 높고, df값이 낮다.(더 중요하다.)
     --> 즉 tf-idf 값이 높다 : 특정 문서 (d_n) 에서 더 중요한 키워드임을 의미.


-- 계산과정
idf(d, t) : log(n) / df(t) + 1
  - n은 전체 문서의 개수

ex) n=1000
idf(d, t) = log(1000 / df(t) + 1)
# 분모값에 1을 더해주는 건, 로그값을 취했을 때 값이 기하급수적으로 커지는 것을 방지하기 위한 수학적 트릭

df(t) = 1, idf(d, t)
'''

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
# 각각의 문서들
documents = [
    'I love you',      # 문서 1
    'I can do it',     # 문서 2
    'I want your love' # 문서 3
]

# DTM (Document term matrix)
# 문서의 개수(m) * 단어의 개수 (n) 차원의 matrix 생성

In [ ]:
v = CountVectorizer() # object 생성

In [ ]:
v.fit_transform(documents).toarray()
# vectors.toarray()

array([[0, 0, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 1]])

In [ ]:
v.vocabulary_ # I라는 단어는 너무 짧아서 빠졌나? 라기보단 stopwords에 걸린듯

{'love': 3, 'you': 5, 'can': 0, 'do': 1, 'it': 2, 'want': 4, 'your': 6}

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer() # object 생성

In [ ]:
tfidf.fit_transform(documents).toarray()

array([[0.        , 0.        , 0.        , 0.60534851, 0.        ,
        0.79596054, 0.        ],
       [0.57735027, 0.57735027, 0.57735027, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.4736296 , 0.62276601,
        0.        , 0.62276601]])

In [ ]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

In [ ]:
# d1, d2, d3는 영화제목
# 각 열은 영화 대사에 등장한 단어 (사랑, 돈, 운명, 증오)
d1 = np.array([1,1,1,0]) # 루트2
d2 = np.array([0,1,1,1])
d3 = np.array([0,3,3,3])
d4 = np.array([0,5,5,5]) # 루트 48

# 유클리디안 거리로는 d2와 d1과 더 가깝다.
# 하지만 코사인 유사도로 계산했을 땐 d2, d4가 더 유사하다고 볼 수 있다.

In [ ]:
# dot product (Ucldiean Distance)
print(f'dot product(d1, d2) = {dot(d1, d2)}')
print(f'dot product(d2, d4) = {dot(d2, d4)}')
print()
# cosine sim
print(f'cosine sim(d1, d2) = {dot(d1, d2) / (norm(d1) * norm(d2))}')
print(f"cosine sim(d2, d4) = {dot(d2, d4) / (norm(d2) * norm(d4))}")

dot product(d1, d2) = 2
dot product(d2, d4) = 15

cosine sim(d1, d2) = 0.6666666666666667
cosine sim(d2, d4) = 1.0


In [ ]:
# Jacaard Sim
# 자카드 유사도: 집합의 원소는 단어에 해당됨, (범위 0-1)
# 내일 과제 (두 문서간의 자카드 유사도, 코사인 유사도 함께 구하기)

'''
자카드유사도 (d1, d2) =  d1.Intersection(d2)_단어  / d1.Union(d2)_단어
'''

d1 = "대한민국 하늘 육지"
d2 = "바다 들판 우주"


In [ ]:
# 오늘 과제2
# 코사인 유사도 기반 와인 추천시스템 개발
# 제공받은 csv파일을 로드

'''
- 상위 5000개의 와인데이터만 추출하여 변수에 저장
- description column 추출
- stopwords(불용어 제거), DTM,
   - 길이가 짧은 애들, 불용어 사전에 등록된 애들 등 제거
- 5000개 문서 중 단어 등장 횟수가 2객 이하 제거
- DTM 구성( 만약 시간이 너무 많이 소요되면, 상위 1000개만)

df.drop(~~, axis=1)

- TFIDF matrix (문서 n * 단어 m)
- cos sim matrix (문서 n * 문서 n) # 문서끼리의 유사도

# ex) 50번에 해당되는 와인과 가장 유사한 와인 10개를 추천해줘.
'''

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/data/datasets/movies_metadata.csv', header=0)
df.head()

<ipython-input-2-fc5e38dd5c67>:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/data/datasets/movies_metadata.csv', header=0)


adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3  False                                                NaN  16000000   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   

                original_title  \
0                    Toy Story   
1                      Jumanji   
2             Grumpier Old Men   
3            Waiting to Exhale   
4  Father of the Bride Part II   

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2  A family wedding reignites the ancient feud be...  ...   1995-12-22   
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4  Just when George Banks has recovered from his ...  ...   1995-02-10   

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]   
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline  \
0  Released                                                NaN   
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   
3  Released  Friends are the people who let you be yourself...   
4  Released  Just When His World Is Back To Normal... He's ...   

                         title  video vote_average vote_count  
0                    Toy Story  False          7.7     5415.0  
1                      Jumanji  False          6.9     2413.0  
2             Grumpier Old Men  False          6.5       92.0  
3            Waiting to Exhale  False          6.1       34.0  
4  Father of the Bride Part II  False          5.7      173.0  

[5 rows x 24 columns]

In [ ]:
len(df.columns)

24

In [ ]:
temp_df = df.iloc[:5000]
temp_df.shape

(5000, 24)

In [ ]:
# 더 쉽게 하는 방법이 있었네
df = df.head(10000)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  10000 non-null  object 
 1   belongs_to_collection  1421 non-null   object 
 2   budget                 10000 non-null  object 
 3   genres                 10000 non-null  object 
 4   homepage               662 non-null    object 
 5   id                     10000 non-null  object 
 6   imdb_id                9999 non-null   object 
 7   original_language      10000 non-null  object 
 8   original_title         10000 non-null  object 
 9   overview               9971 non-null   object 
 10  popularity             10000 non-null  object 
 11  poster_path            9969 non-null   object 
 12  production_companies   10000 non-null  object 
 13  production_countries   10000 non-null  object 
 14  release_date           9995 non-null   object 
 15  rev

In [ ]:
df.isnull().sum()

adult                       0
belongs_to_collection    8579
budget                      0
genres                      0
homepage                 9338
id                          0
imdb_id                     1
original_language           0
original_title              0
overview                   29
popularity                  0
poster_path                31
production_companies        0
production_countries        0
release_date                5
revenue                     0
runtime                     6
spoken_languages            0
status                      8
tagline                  3108
title                       0
video                       0
vote_average                0
vote_count                  0
dtype: int64

In [ ]:
df['overview'] = df.overview.fillna('')

In [ ]:
df.overview.isnull().sum()

0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.feature_extraction.text import

tf_idf = TfidfVectorizer(stop_words='english') # object 생성

In [ ]:
tfidf_mat = tf_idf.fit_transform(df.overview) # TfIdf matrix 생성
tfidf_mat.shape

(10000, 32350)

In [ ]:
tfidf_mat

<10000x32350 sparse matrix of type '<class 'numpy.float64'>'
	with 268918 stored elements in Compressed Sparse Row format>

In [ ]:
cos_sim = cosine_similarity(tfidf_mat, tfidf_mat) # 문서간의 유사도를 비교해야함.

In [ ]:
cos_sim[:5]

array([[1.        , 0.01682915, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01682915, 1.        , 0.04871976, ..., 0.        , 0.01200997,
        0.        ],
       [0.        , 0.04871976, 1.        , ..., 0.        , 0.00735515,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.02578022, ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
# aws - ec2 (유료버전 cloud pc)
# aws 트리 티어 (무료버전)

cos_sim.shape

(10000, 10000)

In [ ]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
cos_sim[0] # 자기 자신과의 유사도는 1 => 빼줘야 함.

array([1.        , 0.01682915, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [ ]:
df[:5].original_title

0                      Toy Story
1                        Jumanji
2               Grumpier Old Men
3              Waiting to Exhale
4    Father of the Bride Part II
Name: original_title, dtype: object

In [ ]:
df.title.head()

0                      Toy Story
1                        Jumanji
2               Grumpier Old Men
3              Waiting to Exhale
4    Father of the Bride Part II
Name: title, dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
data = dict(zip(df.title, df.index))

In [ ]:
i = data['Toy Story']
print(i)

0


In [ ]:
data

In [ ]:
def recommand(t, cosine_sim=cos_sim): # t에는 제목 전달, cosine_sim 선언 및 초기화
  idx = data[t] # 영화 제목에 매칭되는 인덱스값 반환
  print(cosine_sim[idx]) # 근데 사실 nd.array() 자료구조도 기본적으로 global하기 때문에...사용 가능함


In [ ]:
def recommand(t): # t에는 제목 전달, cosine_sim 선언 및 초기화
  idx = data[t] # 영화 제목에 매칭되는 인덱스값 반환
  # print(cos_sim[idx]) # 근데 사실 nd.array() 자료구조는 기본적으로 list와 거의 동일하고,
                       # list 자료구조는 global에서 사용되기 때문에 변수로 지정 안해줘도 됨
  sim_scores = list(enumerate(cos_sim[idx])) # (index, cos_score) 형태로 저장됨.
  temp = sorted(sim_scores, key=lambda x:x[1], reverse=True)
  # print(temp[:11])
  return(temp[:11])

In [ ]:
recommand('Toy Story')

[(0, 1.0000000000000002),
 (2997, 0.45638472239975103),
 (8327, 0.2125051726227112),
 (1071, 0.18331721941453483),
 (3057, 0.14787027144517378),
 (1932, 0.14188013382197434),
 (485, 0.14122665831617187),
 (5797, 0.13658886827487585),
 (7254, 0.1301910487191963),
 (6944, 0.12627898167423743),
 (7615, 0.12460340953655338)]

In [ ]:
recommand_movies = recommand('Toy Story')
for idx, score in recommand_movies[1:]:
  print(df.title[idx])

Toy Story 2
The Champ
Rebel Without a Cause
Man on the Moon
Condorman
Malice
Class of 1984
Africa Screams
Rivers and Tides
The First $20 Million Is Always the Hardest


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/data/datasets/winemag-data-130k-v2.csv', header=0)

In [ ]:
df.shape

(129971, 14)

In [ ]:
df = df.head(5000)

In [ ]:
df.head()

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Unnamed: 0             5000 non-null   int64  
 1   country                4997 non-null   object 
 2   description            5000 non-null   object 
 3   designation            3523 non-null   object 
 4   points                 5000 non-null   int64  
 5   price                  4657 non-null   float64
 6   province               4997 non-null   object 
 7   region_1               4208 non-null   object 
 8   region_2               1956 non-null   object 
 9   taster_name            3969 non-null   object 
 10  taster_twitter_handle  3794 non-null   object 
 11  title                  5000 non-null   object 
 12  variety                5000 non-null   object 
 13  winery                 5000 non-null   object 
dtypes: float64(1), int64(2), object(11)
memory usage: 547.0+

In [ ]:
df.isnull().sum()

Unnamed: 0                  0
country                     3
description                 0
designation              1477
points                      0
price                     343
province                    3
region_1                  792
region_2                 3044
taster_name              1031
taster_twitter_handle    1206
title                       0
variety                     0
winery                      0
dtype: int64

In [ ]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
describe = df.description

In [ ]:
describe

0       Aromas include tropical fruit, broom, brimston...
1       This is ripe and fruity, a wine that is smooth...
2       Tart and snappy, the flavors of lime flesh and...
3       Pineapple rind, lemon pith and orange blossom ...
4       Much like the regular bottling from 2012, this...
                              ...                        
4995    Sweaty and pungent, loaded with overtones of c...
4996    Here's a well-toasted red wine from Southern I...
4997    Candied fruit and caramel ride on the back of ...
4998    This Cabernet Sauvignon-Syrah blend is soft an...
4999    Pungent, zesty and quite varietal in its expre...
Name: description, Length: 5000, dtype: object

In [ ]:
# 전부 소문자로 바꿔주기
describe = describe.apply(lambda x:x.lower())

# word tokenizer로 단어단위로 구분
describe = describe.apply(lambda x:word_tokenize(x))

In [ ]:
# 불용어 제거 및 3글자 이하 버리기
describe = describe.apply(lambda x:[word for word in x if len(word) > 3])

In [ ]:
import nltk
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')
stop_words = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
import re
describe = describe.apply(lambda x: [word for word in x if word not in stop_words])

In [ ]:
describe.head()

0    [aromas, include, tropical, fruit, broom, brim...
1    [ripe, fruity, wine, smooth, still, structured...
2    [tart, snappy, flavors, lime, flesh, rind, dom...
3    [pineapple, rind, lemon, pith, orange, blossom...
4    [much, like, regular, bottling, 2012, comes, a...
Name: description, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vec = TfidfVectorizer()

In [ ]:
# 문자열로 만들기
describe = describe.apply(lambda x: ' '.join(x))

In [ ]:
describe.head()

0    aromas include tropical fruit broom brimstone ...
1    ripe fruity wine smooth still structured firm ...
2    tart snappy flavors lime flesh rind dominate g...
3    pineapple rind lemon pith orange blossom start...
4    much like regular bottling 2012 comes across r...
Name: description, dtype: object

In [ ]:
type(describe[0])

str

In [ ]:
tf_vec = tfidf_vec.fit_transform(describe)

In [ ]:
tf_vec.shape

(5000, 8080)

In [ ]:
tf_vec = tf_vec.toarray()

In [ ]:
describe[0]

'aromas include tropical fruit broom brimstone dried herb palate overly expressive offering unripened apple citrus dried sage alongside brisk acidity'

In [ ]:
temp = [t for t in tf_vec[0] if t > 0]
len(temp)

19

In [ ]:
tf_vec.shape

(5000, 8080)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_sim = cosine_similarity(tf_vec, tf_vec)
cosine_sim.shape

(5000, 5000)

In [ ]:
cosine_sim[0]

array([1.        , 0.01135759, 0.01042356, ..., 0.00721141, 0.        ,
       0.02759952])

In [ ]:
df.title.head()

0                    Nicosia 2013 Vulkà Bianco  (Etna)
1        Quinta dos Avidagos 2011 Avidagos Red (Douro)
2        Rainstorm 2013 Pinot Gris (Willamette Valley)
3    St. Julian 2013 Reserve Late Harvest Riesling ...
4    Sweet Cheeks 2012 Vintner's Reserve Wild Child...
Name: title, dtype: object

In [ ]:
temp = df.title.iloc[0]
temp

'Nicosia 2013 Vulkà Bianco  (Etna)'

In [ ]:
data = dict(zip(df.title, df.index))
data[temp]

0

In [ ]:
def recommand(title): # t에는 제목 전달, cosine_sim 선언 및 초기화
  idx = data[title] # 와인 이름 반환
  # print(cos_sim[idx]) # 근데 사실 nd.array() 자료구조는 기본적으로 list와 거의 동일하고,
                       # list 자료구조는 global에서 사용되기 때문에 변수로 지정 안해줘도 됨
  sim_scores = list(enumerate(cosine_sim[idx])) # (index, cos_score) 형태로 저장됨.
  temp = sorted(sim_scores, key=lambda x:x[1], reverse=True)

  return(temp[1:11])

In [ ]:
recommand(temp)

[(2000, 0.29091252320429173),
 (4033, 0.2485239701894266),
 (1036, 0.24416432060934953),
 (908, 0.22219078073821913),
 (4053, 0.21219280693431058),
 (677, 0.20599018665238691),
 (3908, 0.20559460827468318),
 (1181, 0.1948546039803392),
 (2725, 0.19136170647914286),
 (917, 0.18642716598896744)]

In [ ]:
def get_title(recommanded=recommand):
  result = [df.title.iloc[idx] for idx, cosine_sim in recommanded]
  return result

res = get_title(recommand(temp))
for title in res:
  print(title)

Feudi del Pisciotto 2013 Baglio del Sole Inzolia (Sicilia)
Chateau Ste. Michelle 2015 Horse Heaven Vineyard Sauvignon Blanc (Horse Heaven Hills)
Vivera 2010 Salisire Bianco  (Etna)
Cascina Bruciata 2013  Barbaresco
Cecilia Beretta 2011 Terre di Cariano Riserva  (Amarone della Valpolicella Classico)
Baracchi Riccardo 2011 Smeriglio Riserva Syrah (Cortona)
La Rajade 2014 Friulano (Collio)
Bel Colle 2013 Montersino  (Barbaresco)
MandraRossa 2015 Urra di Mare Sauvignon (Sicilia)
Deltetto 2012 Bussia  (Barolo)
